### ISSUE TITLE
Won't click

### ISSUE THREAD

**Issue by Nokoa** [OutdatedVersion/the-button#1]
I am clicking button and nothing happens please fix

**Comment by OutdatedVersion** [comment]
You'll need to help me rewire the light strip after I find the Pi :)

**Comment by Nokoa** [comment]
Okay

**Comment by Nokoa** [comment]
I been having clicking issues. Your telepathic click detector has been misinterpreting me wanting to click with me wanting to format my computer. Not a major issue. I would however prefer to keep everything I got on my computer.

**Comment by Nokoa** [comment]
I believe I am still having this issue.
